### ISSUE TITLE
FormProductActivity.kt

### ISSUE THREAD

**Issue by andersonFaro9** [alexfelipe/TechStore#2]
**Falta colocar uma intent que direcione para a activity ProductsListActivity onde os dados persistidos aparecem.**

```
inner class SaveNote : AsyncTask<Void, Void, Void>() {
        override fun doInBackground(vararg p0: Void?): Void? {
            val createdProduct = create()
            productDao.add(createdProduct)

           //Manda para acitivity onde os dados ficam persistidos.
            val i = Intent(this@FormProductActivity, ProductsListActivity::class.java) 
            startActivity(i)
            finish()
            return null
        }
    }
```

**Comment by alexfelipe** [comment]
Anderson, nesse caso não precisa, pois a `FormProductActivity` é aberta pela `ProductListActivity`, ou seja, ela está na pilha de Activities, portanto, basta apenas fechá-la com o `finish()` mesmo. [Você pode conferir essa chamada](https://github.com/alexfelipe/TechStore/blob/part-2/app/src/main/java/alexf/com/br/techstore/ui/activity/ProductsListActivity.kt).

**Comment by andersonFaro9** [comment]
bLZA
